### ISSUE TITLE
glibc is missing

### ISSUE THREAD

**Issue by photoszzt** [razaaliraza/ukl#2]
The glibc repo is not in github.

**Comment by rbauduin** [comment]
If others are interested, I used source from https://www.gnu.org/software/libc/sources.html

Git clone then enter the git repo directory and

    mkdir glibc-build
    cd glibc-build/
    ../configure --enable-static-pie --prefix=/tmp

You then get the libc.a file referenced from ukl. (though I still have other problems later :-)

**Comment by jzck** [comment]
> You then get the libc.a file referenced from ukl. (though I still have other problems later :-)

The `libc.a` was obtained from a slightly modified glibc, in order to translate the syscalls prefixed ukl_ (ukl_accept to accept for example). try `grep libc.a ukl_accept` and you will see a match

**Comment by razaaliraza** [comment]
Done
